### ISSUE TITLE
Extending Linear Quantization for Signed Integers

### ISSUE THREAD

**Issue by pabvald** [milankl/LinLogQuantization.jl#12]
hej,

First of all, congratulations on the nice job you've done with this package😺 

Secondly, I was wondering if you would be willing to accept an extension of linear quantization to support signed integers.

**Comment by milankl** [comment]
Hi Pablo, welcome! Thanks, I don't use this package much anymore so I'm more than happy to support many directions if you want to develop this any further.

However, I don't think I can follow you on signed integers? Like do you want to actually use signed integers so that 0xff actually means -1 or just store the bits of linear quantization in signed integers but they still mean unsigned integers? For the latter you can always do things like

```julia
julia> A = LinQuant8Array(rand(5))
5-element LinQuantArray{UInt8, 1}:
 0x37
 0x15
 0x00
 0x7e
 0xff

julia> reinterpret.(Int8, A)
5-element Vector{Int8}:
  55
  21
   0
 126
  -1
```

but it doesn't sound like that's what you're looking for. For the former, using signed integers do you want to mirror the representable range of numbers for positive and negative values? So like, say you do signed 2-bit quantization with min=3, max=4 then
```
 0 = 0b00 => 3
 1 = 0b01 => 4
-1 = 0b11 => -3
-2 = 0b10 => -4
```
?

**Comment by pabvald** [comment]
The former, yes. I want to apply quantization to LLM's embeddings  to be used in a RAG system. So, for 8-bit integers, instead of mapping the `Float32` embeddings to `[0, 255]` (`UInt8`), I would like to map them to `[-128, 127]` (`Int8`). I would also want to include the possibility of indicating the range of the original embeddings to be considered in order to leave outliers out of the quantization.  [Here](https://qdrant.tech/articles/scalar-quantization/) you can see the details of what I would like to implement. 

> Our example shows that 99% of the values come from a [-2.0, 5.0] range. And the conversion to int8 will surely lose some precision, so we rather prefer keeping the representation accuracy within the range of 99% of the most probable values and ignoring the precision of the outliers. There might be a different choice of the range width, actually, any value from a range [0, 1], where 0 means empty range, and 1 would keep all the values. That’s a hyperparameter of the procedure called quantile. A value of 0.95 or 0.99 is typically a reasonable choice, but in general quantile ∈ [0, 1].

Right now, you are always using the minimum and maximum values i.e. range of 100%.

**Comment by milankl** [comment]
> So, for 8-bit integers, instead of mapping the `Float32` embeddings to `[0, 255]` (`UInt8`), I would like to map them to `[-128, 127]` (`Int8`).

So would changing the type parameter `T <: Unsigned` into `T <: Integer` suffice? I don't think so, becauase I'd like to keep the default of using unsigned integers but so that you could do `LinQuantization(Int8, ::Array)` in your case.

The problem I see that in this line

https://github.com/milankl/LinLogQuantization.jl/blob/74c4c009693f058c4fdea3e2911a3c58ddd0a711/src/linquantarrays.jl#L28-L31

what you'd need instead is that minimum is mapped to `0b10...0` (-128 for Int8) then increasingly to `0b11...1` before jumping for the mean to map this to `0b00...0` then increasingly to `0b011...1` for the max. To preserve the order in the signed integer meaning of the bit encoding. 


> I would also want to include the possibility of indicating the range of the original embeddings to be considered in order to leave outliers out of the quantization.

That could be done with `max`, `min` or directly `extrema` as keyword arguments? But note that this probably requires to `clamp` any values in the conversion -- even if they're all in the range. This would slow down the "compression" but maybe it's not too bad.

**Comment by milankl** [comment]
Is that what you're looking for?

```julia
function LinQuantization(
    ::Type{T},
    A::AbstractArray;
    extrema::Tuple = extrema(A),
) where {T<:Signed}
    all(isfinite.(A)) || throw(DomainError("Linear quantization only in (-∞,∞)"))

    # minimum-maximum range of values, calculate or use provided
    Amin, Amax = Float64.(extrema)        

    # inverse spacing, set to zero for no range
    Δ⁻¹ = Amin == Amax ? zero(Float64) : (2^(sizeof(T)*8)-1)/(Amax-Amin)
    
    # preallocate
    Q = similar(A, T)                        

    # map minimum to -128 (for Int8), maximum to 127, 
    for i in eachindex(Q)
        Q[i] = round(T, clamp((A[i]-Amin)*Δ⁻¹ + typemin(T), typemin(T), typemax(T)))
    end

    return Q, Amin, Amax
end
```

This would map out to $[-128, 127]$ by default

```julia
julia> A = rand(5)
julia> LinQuantization(Int8, A)
(Int8[127, 44, -128, -122, -89], 0.02714078648873608, 0.9404354618164285)
```

or you can provide your own range

```julia
julia> A = rand(5)
julia> LinQuantization(Int8, A; extrema=(0.3, 0.6))
(Int8[37, 127, -128, -119, -128], 0.3, 0.6)
```

So it seems only a `+ typmin(T)` is needed which, in the case of unsigned integers is just adding 0 and so maybe even compiled away. Meaning we can just one function for signed and unsigned integers. The `clamp` is needed for the manual extrema, not sure whether we want to branch in case extrema aren't manually set. Maybe would be good to benchmark the difference. Happy for you to turn this into a pull request if that's what you're after!

**Comment by pabvald** [comment]
Yes, that's exactly what I was looking for. I will do the benchmarking and create the PR afterwards.

**Comment by milankl** [comment]
We could probably let multiple dispatch handle the clamp. So if `extrema::Nothing` then calculate them and use a kernel without clamp, if `::Tuple` use a kernel with clamp. That way we get both.
